# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GrvT3GOm0HHcHAix0x3MFpSj7zUNBNFe
"""

!python --version

t, f = True, False
print(type(t))

import torch
torch.cuda.is_available()

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %timeit sum(range(100))

# Commented out IPython magic to ensure Python compatibility.
# %%timeit
# total = 0
# for i in range(1000):
#     for j in range(1000):
#         total += i * (-1) ** j

# Commented out IPython magic to ensure Python compatibility.
def sum_of_lists(N):
    total = 0
    for i in range(5):
        L = [j ^ (j >> i) for j in range(N)]
        total += sum(L)
    return total
# %prun sum_of_lists(1000000)